version: 2.1
orbs:
  aws-terragrunt: smarshorbs/aws-terragrunt@2.2.0
jobs:
  terraform:
    executor: aws-terragrunt/default
    steps:
      - aws-terragrunt/set-up:
          aws-access-key-id: "AKIAYEIH5MU3HRVM3JBS"
          aws-secret-access-key: "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"
          aws-region: "ap-south-1"
          tf-version: 0.13.5
      - run: echo "namespace=\"$NAMESPACE\"" >> ./infra/common/terraform.tfvars
      - run: echo "profile=\"default\"" >> ./infra/common/terraform.tfvars
      - run: cd ./infra && terragrunt apply-all --terragrunt-non-interactive
workflows:
  terraform:
    jobs:
      - terraform:
          context:
            - Dev